### PR TITLE
Adding .envrc to help with dbt-platform commands

### PR DESCRIPTION
**Pull request by chris-pettinga**

### CODE REVIEW

**Review by MattHolmes123 — CHANGES_REQUESTED** [review]
These values are defined in the icms-deploy repo and when I spoke to @acodeninja  he said we should be in that directory when doing all dbt-platform commands apart (apart from one command and I can't remember what he said) :D

**Comment by chris-pettinga** [comment]
> These values are defined in the icms-deploy repo

They are indeed, but we all work in this repo so it would be nice if we could do it all from one place, rather than `cd`ing in an out

**Comment by MattHolmes123** [comment]
> > These values are defined in the icms-deploy repo
> 
> They are indeed, but we all work in this repo so it would be nice if we could do it all from one place, rather than `cd`ing in an out

icms-deploy also defines the version of platform-helper we should use for deployments as well:
https://github.com/uktrade/icms-deploy/blob/main/.copilot-version

**Comment by MattHolmes123** [comment]
Rather than adding this duplication, if it's benificial to you why don't you just create symlinks for the files on your machine?

**Pull request closed without merging**
